name: Laravel

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - .github/**
      - docs/**
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - .github/**
      - docs/**

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --no-scripts
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
    #   php artisan key:generate
    # - name: Composer install laravel-admin
    #   run: composer require nicelizhi/laravel-admin
    # - name: Composer dump-autoload
    #   run: composer dump-autoload
    # - name: Generate key
    #   run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    # - name: Create Database
    #   run: |
    #     mkdir -p database
    #     touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
    - name: Sync to Server and Do it
      uses: appleboy/ssh-action@v1.0.2
      env:
        GITHUB_SHA_X: ${GITHUB_SHA}
      with:
        host: ${{ secrets.SSH_HOST }}  
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.WWW_DIR }} && git pull
           php81 artisan migrate
           vendor/bin/phpunit 
